// This file is auto-generated by the Supabase CLI
// In CI environments, this file is used as a placeholder
// For local development, run: npm run generate-supabase-types

export type Database = {
  public: {
    Tables: {
      // Add your table types here
    }
  }
}
